
import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css'
import Navbar from "./components/navbar";
import Scroller from "./components/scroller";
import type { Metadata } from "next";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  manifest:"/manifest.json",
  title: "Gaupalika",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="stylesheet" type="text/css" href="/assets/css/style.css"></link>
      <body className={inter.className}>
        <Navbar/>
        <Scroller/>
        {children}</body>
    </html>
  );
}
