
import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css'
import Navbar from "./components/navbar";
import Scroller from "./components/scroller";
import type { Metadata, Viewport } from "next";

const APP_NAME = "Gau Palika";
const APP_DEFAULT_TITLE = "My Gau Palika";
const APP_TITLE_TEMPLATE = "%s - Gau Palika";
const APP_DESCRIPTION = "Best Gau Palikain the world!";

export const metadata: Metadata = {
  applicationName: APP_NAME,
  title: {
    default: APP_DEFAULT_TITLE,
    template: APP_TITLE_TEMPLATE,
  },
  description: APP_DESCRIPTION,
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: APP_DEFAULT_TITLE,
    // startUpImage: [],
  },
  formatDetection: {
    telephone: false,
  },
  openGraph: {
    type: "website",
    siteName: APP_NAME,
    title: {
      default: APP_DEFAULT_TITLE,
      template: APP_TITLE_TEMPLATE,
    },
    description: APP_DESCRIPTION,
  },
  twitter: {
    card: "summary",
    title: {
      default: APP_DEFAULT_TITLE,
      template: APP_TITLE_TEMPLATE,
    },
    description: APP_DESCRIPTION,
  },
};

export const viewport: Viewport = {
  themeColor: "#FFFFFF",
};

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Gaupalika",
//   description: "Generated by create next app",
// };


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="stylesheet" type="text/css" href="/assets/css/style.css"></link>
      <body className={inter.className}>
        <Navbar/>
        <Scroller/>
        {children}</body>
    </html>
  );
}
